name: bugsnag-haskell
version: 0.0.4.1
synopsis: Bugsnag error reporter for Haskell
description: Please see README.md
homepage: https://github.com/pbrisbin/bugsnag-haskell#readme
author: Patrick Brisbin
maintainer: pbrisbin@gmail.com
category: Web
license: MIT

dependencies:
  - base >= 4.11.0 && < 5

extra-doc-files:
  - CHANGELOG.md
  - README.md

extra-source-files:
  - test/fixtures/**/*

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

# Doing this via stack.yaml so that other GHC builds don't see it
# ghc-options: -fwrite-ide-info
#   -Weverything
#   -Wno-safe
#   -Wno-unsafe
#   -Wno-missing-import-lists
#   -Wno-missing-safe-haskell-mode
#   -Wno-prepositive-qualified-module
#   -Wno-all-missed-specialisations

library:
  source-dirs: src
  dependencies:
    - Glob >= 0.9.0
    - aeson >= 1.3.0.0
    - bytestring
    - case-insensitive
    - containers
    - http-client
    - http-client-tls
    - http-conduit
    - http-types
    - iproute
    - network
    - parsec
    - template-haskell
    - text
    - th-lift-instances
    - time
    - ua-parser
    - wai

executables:
  example-simple:
    source-dirs: examples/simple
    main: Main.hs
    dependencies:
      - bugsnag-haskell
    when:
      - condition: ! "!(flag(examples))"
        buildable: false

  example-cli:
    source-dirs: examples/cli
    main: Main.hs
    dependencies:
      - bugsnag-haskell
    when:
      - condition: ! "!(flag(examples))"
        buildable: false

  example-warp:
    source-dirs: examples/warp
    main: Main.hs
    dependencies:
      - bugsnag-haskell
      - wai
      - warp
    when:
      - condition: ! "!(flag(examples))"
        buildable: false

  example-yesod:
    source-dirs: examples/yesod
    main: Main.hs
    dependencies:
      - bugsnag-haskell
      - unliftio
      - wai
      - warp
      - yesod-core
    when:
      - condition: ! "!(flag(examples))"
        buildable: false

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec
      - bugsnag-haskell
      - aeson
      - aeson-qq
      - text
      - time
      - unliftio
  doctest:
    main: DocTest.hs
    source-dirs: .
    dependencies:
      - aeson
      - doctest
      - yaml

flags:
  examples:
    description: Build the examples
    manual: false
    default: false
