---
name: bugsnag-haskell
version: 0.0.1.2
synopsis: Bugsnag error reporter for Haskell
description: Please see README.md
homepage: https://github.com/pbrisbin/bugsnag-haskell#readme
author: Patrick Brisbin
maintainer: pbrisbin@gmail.com
category: Web
license: MIT

dependencies:
  - base >= 4.8.0 && < 5

ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - case-insensitive
    - http-client
    - http-client-tls
    - http-conduit
    - http-types
    - iproute
    - network
    - parsec
    - template-haskell
    - text
    - th-lift-instances
    - time
    - ua-parser
    - wai

executables:
  example-simple:
    source-dirs: examples/simple
    main: Main.hs
    dependencies:
      - bugsnag-haskell
    when:
      - condition: ! '!(flag(examples))'
        buildable: false

  example-cli:
    source-dirs: examples/cli
    main: Main.hs
    dependencies:
      - bugsnag-haskell
    when:
      - condition: ! '!(flag(examples))'
        buildable: false

  example-warp:
    source-dirs: examples/warp
    main: Main.hs
    dependencies:
      - bugsnag-haskell
      - wai
      - warp
    when:
      - condition: ! '!(flag(examples))'
        buildable: false

  example-yesod:
    source-dirs: examples/yesod
    main: Main.hs
    dependencies:
      - bugsnag-haskell
      - exceptions
      - unliftio
      - wai
      - warp
      - yesod-core
    when:
      - condition: ! '!(flag(examples))'
        buildable: false

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec
      - bugsnag-haskell
      - aeson
      - aeson-qq
      - text
      - time
  doctest:
    main: DocTest.hs
    source-dirs: .
    ghc-options: -Wall
    dependencies:
      - doctest

flags:
  examples:
    description: Build the examples
    manual: false
    default: false
