---
name: bugsnag-reporter
version: 0.0.1.0
synopsis: Bugsnag reporter
description: Please see README.md
homepage: https://github.com/pbrisbin/bugsnag-reporter#readme
author: Patrick Brisbin
maintainer: pbrisbin@gmail.com
category: Web
license: MIT

dependencies:
  - base >= 4.8.0 && < 5

ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - case-insensitive
    - exceptions
    - http-client
    - http-client-tls
    - http-conduit
    - http-types
    - iproute
    - network
    - parsec
    - template-haskell
    - text
    - th-lift-instances
    - time
    - wai

executables:
  example-simple:
    source-dirs: examples
    main: simple.hs
    dependencies:
      - bugsnag-reporter

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec
      - bugsnag-reporter
      - exceptions
  doctest:
    main: DocTest.hs
    source-dirs: .
    ghc-options: -Wall
    dependencies:
      - doctest
