require-stack-version: ">= 2.1.1"
resolver: lts-15.1
extra-deps:
  - git: https://github.com/pbrisbin/hs-cc-coverage
    commit: a37306a0fd97c74ef97dd683046ca3d833a29840

# Fix weeder with stack-2.0
ghc-options: { "$locals": -ddump-to-file -ddump-hi }
