resolver: lts-19.1

packages:
  - bugsnag
  - bugsnag-wai
  - bugsnag-yesod

extra-deps:
  # For weeder
  - algebraic-graphs-0.5

ghc-options:
  "$locals": >
    -fwrite-ide-info
    -Weverything
    -Wno-all-missed-specialisations
    -Wno-missing-exported-signatures
    -Wno-missing-import-lists
    -Wno-missing-safe-haskell-mode
    -Wno-prepositive-qualified-module
    -Wno-safe
    -Wno-unsafe

flags:
  bugsnag:
    examples: true
  bugsnag-wai:
    examples: true
  bugsnag-yesod:
    examples: true
