resolver: lts-18.28

packages:
  - bugsnag
  - bugsnag-wai
  - bugsnag-yesod

extra-deps:
  # for weeder
  - dhall-1.40.2
  - generic-lens-2.2.0.0
  - generic-lens-core-2.2.0.0

ghc-options:
  "$locals": >
    -fwrite-ide-info
    -Weverything
    -Wno-all-missed-specialisations
    -Wno-missing-exported-signatures
    -Wno-missing-import-lists
    -Wno-missing-safe-haskell-mode
    -Wno-prepositive-qualified-module
    -Wno-safe
    -Wno-unsafe
