resolver: lts-12.2
extra-deps:
  - ua-parser-0.7.5.0
  - git: https://github.com/pbrisbin/hs-cc-coverage
    commit: a37306a0fd97c74ef97dd683046ca3d833a29840
ghc-options:
  "$locals": -fhide-source-paths
