name: bugsnag
version: 0.0.0.1
synopsis: Bugsnag error reporter for Haskell
description: Please see README.md
homepage: https://github.com/pbrisbin/bugsnag-haskell#readme
author: Patrick Brisbin
maintainer: pbrisbin@gmail.com
category: Web
license: MIT

dependencies:
  - base >= 4.11.0 && < 5

extra-doc-files:
  - CHANGELOG.md
  - README.md

extra-source-files:
  - package.yaml
  - test/fixtures/**/*

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: src
  dependencies:
    - Glob >= 0.9.0
    - bugsnag-hs
    - bytestring
    - case-insensitive
    - containers
    - http-client
    - http-client-tls
    - http-types
    - parsec
    - template-haskell
    - text
    - th-lift-instances
    - ua-parser
    - unordered-containers

executables:
  example-simple:
    source-dirs: examples/simple
    main: Main.hs
    dependencies:
      - bugsnag
    when:
      - condition: ! "!(flag(examples))"
        buildable: false

  example-cli:
    source-dirs: examples/cli
    main: Main.hs
    dependencies:
      - bugsnag
    when:
      - condition: ! "!(flag(examples))"
        buildable: false

  # example-warp:
  #   source-dirs: examples/warp
  #   main: Main.hs
  #   dependencies:
  #     - bugsnag
  #     - wai
  #     - warp
  #   when:
  #     - condition: ! "!(flag(examples))"
  #       buildable: false

  # example-yesod:
  #   source-dirs: examples/yesod
  #   main: Main.hs
  #   dependencies:
  #     - bugsnag
  #     - unliftio
  #     - wai
  #     - warp
  #     - yesod-core
  #   when:
  #     - condition: ! "!(flag(examples))"
  #       buildable: false

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec
      - bugsnag
      - text
      - unliftio

flags:
  examples:
    description: Build the examples
    manual: false
    default: false
