name: Release

on:
  push:
    branches: main

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - bugsnag
          - bugsnag-wai
          - bugsnag-yesod

    steps:
      - uses: actions/checkout@v2

      - id: tag
        uses: freckle/haskell-tag-action@v1
        with:
          package-yaml: ${{ matrix.package }}/package.yaml
          tag-prefix: ${{ matrix.package }}-v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.tag.outputs.tag
        uses: freckle/stack-upload-action@v2
        with:
          working-directory: ${{ matrix.package }}
        env:
          HACKAGE_API_KEY: ${{ secrets.HACKAGE_API_KEY }}
          STACK_YAML: ../stack-lts-12.26.yaml
