name: Release

on:
  push:
    branches:
      - main
      - rc/*

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - bugsnag
          - bugsnag-wai
          - bugsnag-yesod

    steps:
      - uses: actions/checkout@v4

      - run: |
          cp -v ${{ matrix.package }}/.releaserc.yml ./.releaserc.yaml

      - id: release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            conventional-changelog-conventionalcommits
            semantic-release-stack-upload
        env:
          FORCE_COLOR: 1
          GITHUB_TOKEN: ${{ github.token }}
          HACKAGE_KEY: ${{ secrets.HACKAGE_API_KEY }}
          STACK_YAML: stack-lts12.yaml
